#!/bin/bash

set -euo pipefail

if [ $BUILDKITE_COMMAND_EXIT_STATUS -ne 0 ] &&
   [ ${BUILDKITE_PLUGIN_CASSANDRA_ECR_CLEANUP:-false} == "true" ]; then
  echo "--- :bat::aws: clean up containers :rage1::rage2::rage3::rage4:"
  # aws_ecr_cleanup
fi
