#!/bin/bash

set -euo pipefail

set +x

CASS_DIR=$(echo $BUILDKITE_PLUGINS |
               jq -r '.[] | keys[] | match(".*cass.*").string' |
               sed -e 's|[./#]|-|g')

cd $BUILDKITE_PLUGINS_PATH/$CASS_DIR

INSTALL_PATH=${BUILDKITE_PLUGIN_CASSANDRA_INSTALL_PATH:-"/var/cass/bin"} make install
export PATH=$INSTALL_PATH:$PATH

CASS_VERSION=$(cat VERSION)

echo ":bat: Using Cass version $CASS_VERSION"

cd $BUILDKITE_BUILD_CHECKOUT_PATH

# required for downloading aws:kms encrypted objects from s3
aws configure set s3.signature_version s3v4

export BUILDKITE_SECRETS_BUCKET=cozero-$PLATFORM-buildkite-secrets
export BUILDKITE_ARTIFACTS_BUCKET=cozero-$PLATFORM-buildkite-artifacts
